name: Artifact Demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a file
        run: echo "Hello from GH-200 artifact demo" > demo.txt

      - name: Show file content
        run: cat demo.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-demo-file
          path: demo.txt
